package com.example.flowable_demo.model;

public enum Role {
    ROLE_BRANCH_STAFF,
    ROLE_CMD_OFFICER,
    ROLE_AUDIT_TEAM,
    ROLE_DEPARTMENT_WORKUNIT,
    ROLE_SERVICE_QUALITY,
    ROLE_CHIEF_COMMITTEE,
    ROLE_ADMIN,
    // Management Roles
    ROLE_BRANCH_MANAGER,
    ROLE_DEPARTMENT_MANAGER,
    ROLE_REGIONAL_DIRECTOR,
    ROLE_DEPARTMENT_DIRECTOR,
    // Executive Roles
    ROLE_CHIEF_BANKING_OFFICER,
    ROLE_CHIEF_OPERATIONS_OFFICER,
    ROLE_EXECUTIVE_COMMITTEE,
    ROLE_CEO_OFFICE
}
